aliases = {
    'meta':'Ayra',
    'speed is everything':'Ayra',
    'serlis':'Seliph',
    'trap':'Lucius',
    'its a trap':'Lucius',
    "it's a trap":'Lucius',
    'frobin':'Robin (F)',
    'fcorrin':'Corrin (F)',
    'fcorn':'Corrin (F)',
    'mrobin':'Robin (M)',
    'mcorrin':'Corrin (M)',
    'mcorn':'Corrin (M)',
    'atiki':'Tiki (Adult)',
    'legal tiki':'Tiki (Adult)',
    'ytiki':'Tiki (Young)',
    'loli tiki':'Tiki (Young)',
    'qr':'Quick Riposte',
    'ld':'Life and Death',
    'lnd':'Life and Death',
    'lad':'Life and Death',
    'qp':'Quickened Pulse',
    'dd':'Distant Defense',
    'dc':'Distant Counter',
    'attactic':'Attack Tactic',
    'siglud':'Sigurd',
    'zigludo':'Sigurd',
    'zigludo-chan-san-sama-senpai-san-sama-san-senpai-chan':'Sigurd',
    'tailtyu':'Tailtiu',
    'chiken':'Fae',
    'floof chiken':'Fae',
    'chicken':'Fae',
    'floof chicken':'Fae',
    'floof dragon':'Fae',
    'fluff chicken':'Fae',
    'fluff dragon':'Fae',
    'fluff chiken':'Fae',
    'scorn':'Corrin (F) (Nohrian Summer)',
    'scorrin':'Corrin (F) (Nohrian Summer)',
    'scam':'Camilla (Spring Festival)',
    'scamilla':'Camilla (Spring Festival)',
    'stiki':'Tiki (Adult) (Ylissean Summer)',
    'sfrederick':'Frederick (Ylissean Summer)',
    'sfred':'Frederick (Ylissean Summer)',
    'sgaius':'Gaius (Ylissean Summer)',
    'srobin':'Robin (F) (Ylissean Summer)',
    'selise':'Elise (Nohrian Summer)',
    'sleo':'Leo (Nohrian Summer)',
    'nowitch':'Nowi (Trick or Defeat!)',
    'floof':'Genny',
    'fluff':'Genny',
    'qr fodder':'Subaki',
    'flying booboo':'Subaki',
    'does her best':'Nino',
    'strongsturdyslow':'Arden',
    'strong, sturdy, slow':'Arden',
    'strong sturdy slow':'Arden',
    'alvis':'Arvis',
    'ploymaster':'Arvis',
    'bbq':'Arvis',
    'doot':'Delthea',
    'thorp':'Tharja',
    'gwendy':'Gwendolyn',
    'babe':'Lukas',
    'ginger stud':'Lukas',
    'you':'Lukas',
    'rein':'Reinhardt',
    'magic is everything':'Reinhardt',
    'marthina':'Marth (Masked)',
    'bridelia':'Cordelia (Bridal Blessings)',
    'broy':'Roy (Brave Heroes)',
    'boy':'Roy (Brave Heroes)',
    'our boy':'Roy (Brave Heroes)',
    'blyn':'Lyn (Brave Heroes)',
    'byn':'Lyn (Brave Heroes)',
    'bike':'Ike (Brave Heroes)',
    'gike':'Ike (Brave Heroes)',
    'blucina':'Lucina (Brave Heroes)',
    'lancina':'Lucina (Brave Heroes)',
    'spurmaster':'Lucina (Brave Heroes)',
    'nohrzura':'Azura (Performing Arts)',
    'axezura':'Azura (Performing Arts)',
    'nohr azura':'Azura (Performing Arts)',
    'axura':'Azura (Performing Arts)',
    'doga':'Draug',
    'dohga':'Draug',
    'pointchoker':'Draug',
    'taco':'Takumi',
    'hnowi':'Nowi (Trick or Defeat!)',
    'hjakob':'Jakob (Trick or Defeat!)',
    'hhenry':'Henry (Trick or Defeat!)',
    'hsakura':'Sakyra (Trick or Defeat!)',
    'bcaeda':'Caeda (Bridal Blessings)',
    'bcharlotte':'Charlotte (Bridal Blessings)',
    'bcordelia':'Cordelia (Bridal Blessings)',
    'attactic':'Attack Tactic',
    'bk':'Black Knight',
    'wlissa':"Lissa (Winter's Envoy)",
    'wchrom':"Chrom (Winter's Envoy)",
    'wtharja':"Tharja (Winter's Envoy",
    'wrobin':"Robin (Winter's Envoy)",
    'xmas lissa':"Lissa (Winter's Envoy)",
    'xmas chrom':"Chrom (Winter's Envoy)",
    'xmas tharja':"Tharja (Winter's Envoy)",
    'xmas robin':"Robin (Winter's Envoy)",
    'thicc':'Thökk'
}
